resource_types:
- name: rsync-resource
  type: docker-image
  source:
      repository: mrsixw/concourse-rsync-resource
      tag: latest
      
resources:
  - name: rfinz-repository
    type: git
    icon: github-circle
    source:
      uri: https://github.com/rfinz/rfinz.git
  - name: server-deploy
    type: rsync-resource
    source:
      server: {{server-address}}
      user: freebsd
      base_dir: /home/freebsd/sync
      disable_version_path: true
      private_key: {{server-key}}
    
jobs:
- name: build-website
  public: true
  plan:
    - get: rfinz-repository
      trigger: true
    - task: build
      config:
        platform: linux
        image_resource:
          type: registry-image
          source: { repository: "rfinz/builder"}
        inputs:
          - name: rfinz-repository
        outputs:
          - name: out
        run:
          path: /bin/sh
          args:
            - -c
            - |
              cd rfinz-repository/jekyll/
              bundle install
              npm install
              bundle exec jekyll build
              cp -r _site/* ../../out
            
    - put: server-deploy
      params: {sync_dir: "out"}
            
