resource_types:
- name: rsync-resource
  type: docker-image
  source:
      repository: mrsixw/concourse-rsync-resource
      tag: latest
      
resources:
- name: rfinz-repository
  type: git
  icon: github-circle
  source:
    uri: https://github.com/rfinz/rfinz.git
- name: server-deploy
  type: rsync-resource
  source:
    server: rfinz.me
    base_dir: www
    disable_version_path: true
    private_key: {{production-server-key}}
    
jobs:
- name: build-website
  public: true
  plan:
    - get: rfinz-repository
      trigger: true
    - task: build
      platform: linux
      inputs:
        - rfinz-repository
      config:
        image-resource:
          type: registry-image
          source: { repository: "jekyll/builder:4.0" }
      run:
        path: /bin/sh
        args:
          - -c
          - |
            apk --update add file imagemagick
            bundle exec jekyll build
    - put: 
        params: {"sync_dir": "out", "rsync_opts": "--usermap=username:rfinz"}
            
